using System;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Lite.Validation.Rules.Inline;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lite.Validation.SourceGenerator;

/// <summary>
/// Generates ICustomInline&lt;TType,TProperty&gt; and Inline(...) implementations
/// for simple custom rules marked with [InlineableRule].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class RuleInlineSourceGenerator : IIncrementalGenerator
{
    private const string InlineableRuleAttributeName = "Lite.Validation.Rules.Inline.InlineableRuleAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                static (ctx, ct) => TryGetRuleInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(candidates, static (spc, info) => Emit(spc, info));
    }

    private static RuleInlineInfo? TryGetRuleInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) is not INamedTypeSymbol symbol)
            return null;

        // Must be partial
        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        // Must have [InlineableRule]
        var hasAttribute = symbol
            .GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == InlineableRuleAttributeName);
        if (!hasAttribute)
            return null;

        // Only handle generic rules with two type arguments: Rule<TType,TProperty>
        if (!symbol.IsGenericType || symbol.TypeArguments.Length != 2)
            return null;

        // Find simple expression-bodied IsSatisfiedBy(TType target, TProperty value)
        var isSatisfied = symbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m =>
                m.Name == "IsSatisfiedBy" &&
                m.Parameters.Length == 2 &&
                m.ReturnType.SpecialType == SpecialType.System_Boolean);

        if (isSatisfied is null)
            return null;

        // Find syntax node to extract expression body
        if (isSatisfied.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax(ct) is not MethodDeclarationSyntax methodSyntax)
            return null;

        if (methodSyntax.ExpressionBody is not ArrowExpressionClauseSyntax arrow)
            return null; // only expression-bodied methods are supported

        var bodyText = arrow.Expression.ToString();

        // Replace parameter names with canonical target/value for generator use
        var pTarget = isSatisfied.Parameters[0].Name;
        var pValue = isSatisfied.Parameters[1].Name;
        bodyText = ReplaceWord(bodyText, pTarget, "target");
        bodyText = ReplaceWord(bodyText, pValue, "_v");

        return new RuleInlineInfo(
            ns: symbol.ContainingNamespace?.ToDisplayString() ?? "",
            className: symbol.Name,
            tType: symbol.TypeArguments[0].ToDisplayString(),
            tProp: symbol.TypeArguments[1].ToDisplayString(),
            ruleName: symbol.Name,
            bodyExpression: bodyText);
    }

    private static string ReplaceWord(string text, string word, string replacement)
        => Regex.Replace(text, $@"\b{Regex.Escape(word)}\b", replacement);

    private static void Emit(SourceProductionContext ctx, RuleInlineInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using Lite.Validation.Rules.Inline;");
        sb.AppendLine("using Lite.Validation.Fluent;");
        sb.AppendLine();

        var hasNs = !string.IsNullOrEmpty(info.Namespace);
        if (hasNs)
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        var i = hasNs ? "    " : "";

        sb.AppendLine($"{i}partial class {info.ClassName}<TType, TProperty> : ICustomInline<TType, TProperty>");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{i}    /// <summary>");
        sb.AppendLine($"{i}    /// Source-generated inline body for {info.RuleName}.");
        sb.AppendLine($"{i}    /// Mirrors the expression-bodied IsSatisfiedBy implementation.");
        sb.AppendLine($"{i}    /// </summary>");
        sb.AppendLine($"{i}    public static void Inline(in RuleInlineContext ctx)");
        sb.AppendLine($"{i}    {{");
        sb.AppendLine($"{i}        var w = ctx.Writer;");
        sb.AppendLine($"{i}        var target = ctx.TargetName;");
        sb.AppendLine($"{i}        var _v = ctx.ValueName;");
        sb.AppendLine($"{i}        var result = ctx.ResultName;");
        sb.AppendLine($"{i}        var prop = ctx.PropertyPathExpression;");
        sb.AppendLine($"{i}        var details = InlineHelpers.CoalesceDetails(ctx.DetailsExpression);");
        sb.AppendLine($"{i}        var cascade = ctx.RuleLevelCascadeVarName;");
        sb.AppendLine();
        sb.AppendLine($"{i}        // {info.RuleName}");
        sb.AppendLine($"{i}        if (!({info.BodyExpression}))");
        sb.AppendLine($"{i}        {{");
        sb.AppendLine($"{i}            result.Add(prop, details);");
        sb.AppendLine($"{i}            if (cascade == CascadeMode.Stop) return;");
        sb.AppendLine($"{i}        }}");
        sb.AppendLine($"{i}    }}");
        sb.AppendLine($"{i}}}");

        if (hasNs)
            sb.AppendLine("}");

        ctx.AddSource($"{info.ClassName}.Inline.g.cs", sb.ToString());
    }
}

internal sealed class RuleInlineInfo
{
    public string Namespace { get; }
    public string ClassName { get; }
    public string TargetTypeName { get; }
    public string PropertyTypeName { get; }
    public string RuleName { get; }
    public string BodyExpression { get; }

    public RuleInlineInfo(
        string ns,
        string className,
        string tType,
        string tProp,
        string ruleName,
        string bodyExpression)
    {
        Namespace = ns;
        ClassName = className;
        TargetTypeName = tType;
        PropertyTypeName = tProp;
        RuleName = ruleName;
        BodyExpression = bodyExpression;
    }
}

